name: ExploitFixer
description: Protect your Minecraft server from exploits and crashers
author: LinsaFTW
version: 2.2.2
url: https://github.com/arkflame/ExploitFixer
main: dev._2lstudios.exploitfixer.ExploitFixer
api: "1.18"
api-version: "1.18"
softdepend: [HamsterAPI]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]
