name: Build plugin from POM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build plugin with Maven
        run: mvn clean install
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v3
        with:
          path: target/exploitfixer-*.jar
