name: Build plugin from POM
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        id: checkout-source-repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        id: setup-jdk17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Check for new release
        id: check-release
        run: |
          RECENT_COMMIT=$(git log -2 --pretty=format:"%s" | sed -n '2 p')
          if [[ $RECENT_COMMIT =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
              echo "There is a new release $RECENT_COMMIT to be built"
          else
              echo "There is no new release to be built"
          fi
      - name: Build plugin with Maven
        if: steps.check-release.outputs.match == 'true'
        id: build-plugin
        run: mvn clean install
      - name: Upload plugin artifact
        id: upload-artifact
        if: steps.check-release.outputs.match == 'true'
        uses: actions/upload-artifact@v3
        with:
          path: target/exploitfixer-*.jar
